### ISSUE TITLE
Pins

### ISSUE THREAD

**Issue by tommywatson** [JediMasterPatrick/Gonk#1]
The info below says  6,7,8,9 are available and pins 14-20...

I modified the code, I setup a TEST_PIN define at the top,
https://github.com/JediMasterPatrick/Gonk/blob/First/Gonk.ino#L7

Can you run it, change the value of TEST_PIN from 14 to 15 and try it, through 20... See what pins up there work.

https://learn.adafruit.com/adafruit-wave-shield-audio-shield-for-arduino/faq
What pins are used by the shield?
Pins 13, 12, 11 are always used by the SD card (they are the only pins that have a high speed SPI interface). Then there are 5 other pins used to talk to the DAC and SD card, but they can be set to connect to any arduino pin. However, by default, the library is configured to use pins 10 (for SD card) and pins 2, 3, 4 and 5 for the DAC. To chanage these pins requires modifying the library - the pins are referenced by their 'hardware' pin names (ie PORTD, etc) not by arduino pins. 

That means pins 6, 7, 8, 9 and the 6 analog in pins (also known as digital i/o pins 14-20) are available.

**Comment by JediMasterPatrick** [comment]
Before I do this, you realize that the wave shield is not the shield I'm
using for the gonk, right?  That is the music maker shield.  The wave
shield is being used for the voice changer.

**Comment by tommywatson** [comment]
Haha, nope, I thought the link you sent was for your shield...

**Comment by JediMasterPatrick** [comment]
Here is the code for the gpio.  It is their examle.

#include <SPI.h>
#include <Adafruit_VS1053.h>
#include <SD.h>

// These are the pins used for the breakout example
#define BREAKOUT_RESET  9      // VS1053 reset pin (output)
#define BREAKOUT_CS     10     // VS1053 chip select pin (output)
#define BREAKOUT_DCS    8      // VS1053 Data/command select pin (output)
// These are the pins used for the music maker shield
#define SHIELD_RESET  -1      // VS1053 reset pin (unused!)
#define SHIELD_CS     7      // VS1053 chip select pin (output)
#define SHIELD_DCS    6      // VS1053 Data/command select pin (output)

// These are common pins between breakout and shield
#define CARDCS 4     // Card chip select pin
// DREQ should be an Int pin, see
http://arduino.cc/en/Reference/attachInterrupt
#define DREQ 3       // VS1053 Data request, ideally an Interrupt pin

Adafruit_VS1053_FilePlayer musicPlayer =
  // create breakout-example object!
  Adafruit_VS1053_FilePlayer(BREAKOUT_RESET, BREAKOUT_CS, BREAKOUT_DCS,
DREQ, CARDCS);
  // create shield-example object!
  //Adafruit_VS1053_FilePlayer(SHIELD_RESET, SHIELD_CS, SHIELD_DCS, DREQ,
CARDCS);

void setup() {
  Serial.begin(9600);
  Serial.println("VS1053 GPIO test");

  // disable the card (we won't be using it)
  pinMode(CARDCS, OUTPUT);
  digitalWrite(CARDCS, HIGH);

  // initialise the music player
  if (!musicPlayer.begin()) {
    Serial.println("VS1053 not found");
    while (1);  // don't do anything more
  }

  musicPlayer.sineTest(0x44, 500);    // Make a tone to indicate VS1053 is
working
}

void loop() {
  for (uint8_t i=0; i<8; i++) {
    musicPlayer.GPIO_pinMode(i, OUTPUT);

```
musicPlayer.GPIO_digitalWrite(i, HIGH);
Serial.print("GPIO: "); Serial.println(musicPlayer.GPIO_digitalRead(i));
musicPlayer.GPIO_digitalWrite(i, LOW);
Serial.print("GPIO: "); Serial.println(musicPlayer.GPIO_digitalRead(i));

musicPlayer.GPIO_pinMode(i, INPUT);

delay(100);
```

  }
}

**Comment by tommywatson** [comment]
Okay, try that, GPIO pins 0, and 1 should play the same as pin 12

**Comment by JediMasterPatrick** [comment]
This mostly works.  There is no gpio 0.  Also, GPIO 1 puts the thing in midi mode.  So I changed it to 2 & 3.  Those work just fine!
This is good news.  GPIO can only be used for lights and simple buttons.  So pins 0, 2, 5 & 12 can be freed up for other sensors and lights.
What would be cool also is to free up 0 since there is a reset on the board.

**Comment by tommywatson** [comment]
Hahaha! Coolio!

You can free up pin 0, but you need a pin to start/stop the noise, correct?

On Sun, Sep 27, 2015 at 2:21 PM, JediMasterPatrick <notifications@github.com

**Comment by JediMasterPatrick** [comment]
So I changed gpio2 to be pin 1 tracks.  gpio3 to be pin 11.  Now I have 5 sets of interrrupts working

**Comment by JediMasterPatrick** [comment]
there is a reset button on the board
It just needs to be called out.
